# Generated by Django 4.1.3 on 2022-11-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receitamodel_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitamodel',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
    ]
