# Generated by Django 4.1.3 on 2022-11-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0003_receitamodel_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitamodel',
            name='imagem_receita',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y'),
        ),
    ]
